### ISSUE TITLE
Retrain Semantic Segmentation for Stanford-2D-3D-S show error "data_lists/pano/fold1/train.txt not found"

### ISSUE THREAD

**Issue by sandynctu** [meder411/Tangent-Images#4]
Hi,

I want to retrain the semantic segmentation experiments using the Stanford dataset.
However, after filling the DATA_ROOT parameters on the config file, it shows "data_lists/pano/fold1/train.txt not found."
Is the training file from Stanford, or you generate it?

Thanks.

**Comment by meder411** [comment]
Whoops, that’s on me. I’ll upload those file lists when I have a chance later today

**Comment by meder411** [comment]
I haven't forgotten about this. Just haven't had access to my file server in a few days. I'll post these lists when I can. In the meantime, these are just generated from the published folds of the Stanford 2D-3D-S dataset. You can generate the files yourself in the meantime if you like

**Comment by sandynctu** [comment]
Thank you for your reply. What is the format of the train.txt?
It is "<rgb file>,<depth file>,<semantic file>" ?

**Comment by meder411** [comment]
That looks right. Each row is a new datum, where each relative path from the root directory is comma-separated

**Comment by meder411** [comment]
Yeah its:

path/to/rgb, path/to/depth, path/to/semantic, path/to/pose_json

**Comment by sandynctu** [comment]
I already generate the train.txt file (the separator should be space, not comma).
However, I got this error:

Caching data to /media/commlab/TenTB/home/sandy/dataset/stanford2d3ds/XYZ/cache/stanford/pano/with_depth/scale_factor_0.25.....
  0%|                                                                                                                                                        | 0/786 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 105, in <module>
    cfg, num_gpus, args.distributed, is_train=True)
  File "/media/commlab/TenTB/home/sandy/program/Tangent-Images/experiments/semantic_segmentation/ss/data/build.py", line 95, in build_dataloader
    cache_dataset(dataset)
  File "/media/commlab/TenTB/home/sandy/program/Tangent-Images/experiments/semantic_segmentation/ss/data/build.py", line 24, in cache_dataset
    sample = dataset.__getitem__(i, tocache=True)
  File "/media/commlab/TenTB/home/sandy/program/Tangent-Images/experiments/semantic_segmentation/ss/data/stanford.py", line 189, in __getitem__
    mode='nearest').squeeze(0)
  File "/media/commlab/TenTB/home/sandy/anaconda3/envs/tangent-images/lib/python3.7/site-packages/torch/nn/functional.py", line 2502, in interpolate
    return torch._C._nn.upsample_nearest3d(input, _output_size(3))
RuntimeError: Input and output sizes should be greater than 0, but got input (D: 3, H: 2048, W: 4096) output (D: 0, H: 512, W: 1024)

Can you help me to solve this error?
Thanks in advance

**Comment by meder411** [comment]
[This commit](https://github.com/meder411/Tangent-Images/commit/a80cf4cf5ba405f6ccede638cdab716131adb779) should resolve your initial issue with the data lists.

Regarding your section error, it looks like an issue with the shape of your tensor going into the PyTorch interpolate function. I don't see it on my end with PyTorch 1.5.0. I'd inspect the shape of the tensor and ensure that it contains the correct information as well.
